name: worldResidenceManager
version: '1.0.0'
main: com.chiliasmstudio.worldResidenceManager.WorldResidenceManager
api-version: '1.21'
folia-supported: true
dependencies:
  server:
    Residence:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: true
      join-classpath: true